// Generated by CoffeeScript 1.6.3
var commitTreeEntry, git, refTreeEntry, resolve, treeEntry;

git = require('gitteh-promisified');

resolve = require('kew').resolve;

treeEntry = function(tree, path) {
  var entry, _i, _len, _ref;
  if (!Array.isArray(path)) {
    path = path.split('/').map(function(v) {
      if (v === '.') {
        return '';
      } else {
        return v;
      }
    }).filter(Boolean);
  }
  if (path.length === 0) {
    return tree;
  }
  _ref = tree.entries;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    entry = _ref[_i];
    if (entry.name === path[0]) {
      if (path.length === 1) {
        if (entry.type === 'blob') {
          return resolve(entry);
        } else if (entry.type === 'tree') {
          tree.repository.tree(entry.id);
        }
      } else if (path.length > 1 && entry.type === 'tree') {
        return tree.repository.tree(entry.id).then(function(tree) {
          return treeEntry(tree, path.slice(1));
        });
      }
    }
  }
  return resolve(void 0);
};

commitTreeEntry = function(commit, path) {
  return commit.tree().then(function(tree) {
    return treeEntry(tree, path);
  });
};

refTreeEntry = function(ref, path) {
  return ref.repository.commit(ref.target).then(commit)(function() {
    return commitTreeEntry(commit, path);
  });
};

module.exports = {
  treeEntry: treeEntry,
  refTreeEntry: refTreeEntry,
  commitTreeEntry: commitTreeEntry
};
