// Generated by CoffeeScript 1.6.3
var equal, git, ok, path, treeEntry, _ref;

_ref = require('assert'), ok = _ref.ok, equal = _ref.equal;

path = require('path');

git = require('gitteh-promisified');

treeEntry = require('./index').treeEntry;

describe('gitteh-tree-entry', function() {
  var tree;
  tree = git.openRepository(path.join(__dirname, '.git')).then(function(repo) {
    return repo.commit('34ee62d4b862d28a3681550275cc77675989daf7');
  }).then(function(commit) {
    return commit.tree();
  });
  it('resolves .', function(done) {
    return tree.then(function(tree) {
      return treeEntry(tree, '.');
    }).then(function(entry) {
      ok(entry);
      return equal(entry.id, 'e157dc65f02f6041c8f042b24874b044dbb63bde');
    }).fin(done).end();
  });
  it('resolves empty', function(done) {
    return tree.then(function(tree) {
      return treeEntry(tree, '');
    }).then(function(entry) {
      ok(entry);
      return equal(entry.id, 'e157dc65f02f6041c8f042b24874b044dbb63bde');
    }).fin(done).end();
  });
  it('resolves file', function(done) {
    return tree.then(function(tree) {
      return treeEntry(tree, 'package.json');
    }).then(function(entry) {
      equal(entry.name, 'package.json');
      return ok(entry);
    }).fin(done).end();
  });
  return it('resolves file prefixed with .', function(done) {
    return tree.then(function(tree) {
      return treeEntry(tree, './package.json');
    }).then(function(entry) {
      equal(entry.name, 'package.json');
      return ok(entry);
    }).fin(done).end();
  });
});
